spring.application.name=demo
server.port=8100

# 1. Database Connection
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.sdgleuyvzbgghhkbrfxi
spring.datasource.password=root123789ytykh
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true